config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  get 'sessions/new'
  get 'sessions/create'
  get('/', {to: 'posts#index', as: :root})
  get 'posts/new'
    

  resources :posts do
  resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_admin?
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, Post) do |post|
      post.user == user
    end

    can :crud, Comment do |comment|
      comment.user == user 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    validates(:title, presence: true, uniqueness: true)
    validates(:body, presence: true, length: {minimum: 50})

    has_many :comments, dependent: :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts, dependent: :nullify
    has_many :comments, dependent: :nullify

    validates :email, presence: true, uniqueness: true,
              format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    def current_user
        if session[:user_id].present?
            @current_user || User.find_by(id: session[:user_id])
        end
        
    end
    helper_method(:current_user)

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
            flash[:danger] = "You must sign in or sign up first!"
            redirect_to new_session_path
        end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize!, only: [:destroy]

    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.new comment_params
        @comment.post = @post
        @comment.user = current_user

        if @comment.save
            redirect_to post_path(@post)
        else
            @comments = @post.comments.order(created_at: :desc)
            render 'posts/show'
        end
    end
    
    def destroy
        @comment = Comment.find params[:id]
        if can? :crud, @answer
            @comment.destroy
            redirect_to post_path(@comment.post)
        else
            redirect_to root_path, alert: 'Not authorized'
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end

    def authorize!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]

    def new
        @post=Post.new
    end

    def index
        @posts=Post.all
    end

    def edit 
    end

    def update
        post_params = params.require(:post).permit(:title, :body)
        if @post.update post_params
            redirect_to post_path(@post)
        else
            render :edit
        end 
    end

    def create
        @post=Post.new post_params
        @post.user = current_user

        if @post.save
            flash[:notice] = "post created successfully"

            redirect_to post_path(@post)
        else
            render :new
        end            
    end

    def show
        @comment = Comment.new
        @comments = @post.comments.order(created_at: :desc)
    end

    def destroy
        @post.destroy
        redirect_to posts_path
      end

    private 

    def post_params
        params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find(params[:id])
    end

    def authorize!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @post)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by_email params[:email]
      if user&.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Logged In"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out!"
    end
  
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
        @user = User.new
    end

    def create
        @user = User.new user_params

        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Logged in!"
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update name_params
            redirect_to root_path, notice: "Updated!"
        else
            render :edit
        end
    end 

        private

        def user_params
            params.require(:user).permit(
              :name,
              :email,
              :password,
              :password_confirmation
            )
        end

        def name_params
            params.require(:user).permit(
                :name, 
                :email
            )
        end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <nav>
  <div class="branding">
  <%= link_to "Blog on Rails", root_path %>
  </div>
  

  <div class="menu">
    <%= link_to "Home", root_path %>
    &emsp;
    <%= link_to 'New Post', new_post_path %>
    &emsp;
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>
    <%#= flash[:notice] || flash[:alert] %>
      <% if user_signed_in?%>
        Hello <%= link_to current_user.name, edit_user_path(current_user) %>,
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: "Are you sure you want to log out?"}%>
      <%else%>
        <%= link_to "Login", new_session_path %> &emsp;
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </div>

  </nav>
  <hr>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>

  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @post do |f| %>
  <div class="col-xs-4">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="col-xs-4">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="card-container">
<% @posts.each do |post|  %>
  <div class="card">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= post.body %></p>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Posts</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<p><%= time_ago_in_words(@post.created_at)%> ago</p>
<h4>Created by: <%= @post.user.name  || 'DELETED'%></h4>
<% if can? :crud, @post %>
<%= link_to "Edit", edit_post_path(@post), class: "btn-med"%>
<%= link_to "Delete", post_path(@post), class: "btn-med", method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<%= form_with(model: [@post, @comment], local: true) do |f| %>
<% if @comment.errors.any? %>
<br>
  <ul>
    <% @comment.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<br>
<div class="form-group">
  <%= f.text_area(
  :body,
  cols: 50,
  rows: 5,
  placeholder: "What are your thoughts?",
  class: "form-control"
  ) %>
</div>
<%= f.submit class: "btn-med" %>
<% end %>

<hr />

<ul class="list-group">
  <% @comments.each do |comment| %>
    <li>
      <p class="list-group-item">
        <%= comment.body %> <br />
         Commented <%= time_ago_in_words(comment.created_at) %> ago
        </small>
        ●
        <% if can? :crud, comment %>
        <small>
        <%= link_to(
          "Delete",
          post_comment_path(@post, comment),
          method: :delete,
          data: {
            confirm: "Are you sure?"
          }
        ) %>
      </small>
      <% end %>
      </p>
    </li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, local: true do |f| %>

    <% if @user.errors.any?%>
        <p>
            <%= @user.errors.full_messages.join(', ')%>
        </p>
    <% end %>


    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>


    <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
    </div>

    <%= f.submit "Edit User", class: "btn btn-primary" %>
    <% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>

    <% if @user.errors.any?%>
        <p>
            <%= @user.errors.full_messages.join(', ')%>
        </p>
    <% end %>


    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>


    <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
    </div>

    <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>

    <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit class: "btn btn-primary" %>
    <% end %>